### ISSUE TITLE
Feature list (+todo features)

### ISSUE THREAD

**Issue by kenrick95** [DroidCare/dc#1]
- [x] POST user/register
- [x] POST user/login
- [x] POST user/logout
- [x] POST user/update
- [x] POST user/[i:id]
- [x] POST appointment/new
- [x] GET appointment/attachment/[s:attachment_id]
- [x] POST appointment/edit
- [x] POST appointment/cancel
- [x] POST appointment/status # update appointment status
- [x] POST appointment/[i:id]
- [x] POST appointment/user/[i:user_id] # list down appointments by user_id (if user_type is 'patient') OR assigned to user_id (if user_type is 'consultant')

-----

Extras:
- [x] GET appointment/timeslot/[i:user_id] ? Get available time slot for certain consultant; fix the time slot duration (**NOTE**: Implemented to get consultant's **UNAVAILABLE** time slot)
- ~~[ ]GET appointment/consultant/[s:date_time] ? Get available consultants for certain date_time~~ (WONT IMPLEMENT)

**Comment by kenrick95** [comment]
Question:
- Should consultant or patient the one who put `remarks`?
